#!/bin/bash


#   .--section funcs-------------------------------------------------------.
#   |                   _   _                __                            |
#   |     ___  ___  ___| |_(_) ___  _ __    / _|_   _ _ __   ___ ___       |
#   |    / __|/ _ \/ __| __| |/ _ \| '_ \  | |_| | | | '_ \ / __/ __|      |
#   |    \__ \  __/ (__| |_| | (_) | | | | |  _| |_| | | | | (__\__ \      |
#   |    |___/\___|\___|\__|_|\___/|_| |_| |_|  \__,_|_| |_|\___|___/      |
#   |                                                                      |
#   '----------------------------------------------------------------------'


function ercole_alarm() {

    QUERY_CRITICAL="select count(*) from alert where severity='CRITICAL' and status <> 'ACK';"
    QUERY_WARNING="select count(*) from alert where severity='WARNING' and status <> 'ACK';"
    CRITICAL=$(echo -e  "$QUERY_CRITICAL" | su - "$DBUSER" -c "$psql -t -X -d $PGDATABASE ${EXTRA_ARGS} -q -A -F';'")
    WARNING=$(echo -e  "$QUERY_WARNING" | su - "$DBUSER" -c "$psql -t -X -d $PGDATABASE ${EXTRA_ARGS} -q -A -F';'")

}

function format_output() {

  if [[ $CRITICAL -gt 0 ]]; then
    echo "2 Ercole-alarm - CRIT Found $CRITICAL Critical event"
  elif [[ $WARNING -gt 0 ]]; then
    echo "1 Ercole-alarm - WARN Found $WARNING Warning event"
  else
    echo "0 Ercole-alarm - OK There aren't event"
  fi

}


function ercole_main() {

    if [ -z "$DBUSER" ] || [ -z "$PGDATABASE" ] ; then
        exit 0
    fi

    EXTRA_ARGS=""
    if [ ! -z "$PGUSER" ]; then
        EXTRA_ARGS=$EXTRA_ARGS" -U $PGUSER"
    fi
    if [ ! -z "$PGPORT" ]; then
        EXTRA_ARGS=$EXTRA_ARGS" -p $PGPORT"
    fi

    ercole_alarm
    format_output

}

#.
#   .--main----------------------------------------------------------------.
#   |                                       _                              |
#   |                       _ __ ___   __ _(_)_ __                         |
#   |                      | '_ ` _ \ / _` | | '_ \                        |
#   |                      | | | | | | (_| | | | | |                       |
#   |                      |_| |_| |_|\__,_|_|_| |_|                       |
#   |                                                                      |
#   '----------------------------------------------------------------------'


MK_CONFFILE=$MK_CONFDIR/ercole.cfg
if [ -e "$MK_CONFFILE" ]; then

    psql="/bin/psql"
    DBUSER=$(grep DBUSER "$MK_CONFFILE" | sed 's/.*=//g')
    PGUSER=$(grep PGUSER "$MK_CONFFILE" | sed 's/.*=//g')
    PGDATABASE=$(grep PGDATABASE "$MK_CONFFILE" | sed 's/.*=//g')
    PGPORT=$(grep PGPORT "$MK_CONFFILE" | sed 's/.*=//g')

    ercole_main

else
    echo "MK_CONFIG FILE NOT FOUND"
fi
